-- Customer Behavior
-- 1.  What is the repeat purchase rate — how many customers ordered more than once?

SELECT 
    COUNT(CASE WHEN order_count > 1 THEN 1 END) AS repeat_customers,
    COUNT(*) AS total_customers,
    ROUND(
        COUNT(CASE WHEN order_count > 1 THEN 1 END) * 100.0 / COUNT(*), 
    2) AS repeat_rate_pct FROM
 (SELECT customer_unique_id,COUNT(*) as order_count FROM orders o
 JOIN customers c
 on c.customer_id = o.customer_id
 group by customer_unique_id
)

-- 2.  What is the average number of days between a customer's first and second order?

SELECT avg(date_diff('day', 
    CAST(first_order_purshase_date AS TIMESTAMP), 
    CAST(second_order_purshase_date AS TIMESTAMP)
) 
)AS days_diff from(
SELECT customer_unique_id , min(case when rank_order = 1 then order_purchase_timestamp else null end) as first_order_purshase_date, min(case when rank_order = 2 then order_purchase_timestamp else null end) as second_order_purshase_date, count(*) FROM (
SELECT c.customer_unique_id, row_number () over(partition by c.customer_unique_id order by order_purchase_timestamp) rank_order , order_purchase_timestamp FROM orders o
 JOIN customers c
 on c.customer_id = o.customer_id) group by customer_unique_id  having count(customer_unique_id) >= 2)


-- 3.  Which cities have the highest average order value?

SELECT * FROM (
    SELECT 
        c.customer_city,
        ROUND(AVG(order_total), 2) AS avg_order_value,
        COUNT(DISTINCT o.order_id) AS total_orders
    FROM orders o
    JOIN customers c ON c.customer_id = o.customer_id
    JOIN (
        SELECT order_id, SUM(price) AS order_total
        FROM order_items
        GROUP BY order_id
    ) AS order_totals ON order_totals.order_id = o.order_id
    GROUP BY c.customer_city
    ORDER BY avg_order_value DESC
) AS city_orders
WHERE total_orders >= 50  -- only cities with meaningful volume
ORDER BY avg_order_value DESC
LIMIT 10


-- i have removed the cities with less than 50 orders to ensure that the average order value is based on a significant number of transactions, which provides a more reliable insight into customer behavior in those cities.
-- 

-- 4.  What percentage of customers never received their order on time?

select sum(case when order_delivered_on_time = 0 then 1 else 0 end )*100.0/COUNT(customer_id) as never_on_time_pct
from(
select customers.customer_id, sum(case when 
    CAST(order_delivered_customer_date AS TIMESTAMP) > 
    CAST(order_estimated_delivery_date AS TIMESTAMP) then 0 else 1 end) as order_delivered_on_time from orders
    join customers on orders.customer_id = customers.customer_id
    where order_status = 'delivered'AND order_delivered_customer_date IS NOT NULL
AND order_estimated_delivery_date IS NOT NULL

    group by customers.customer_id)

-- added the condition to only include delivered orders with valid delivery dates to ensure that the analysis accurately reflects the percentage of customers who never received their orders on time, based on reliable data.
-- also added the condition to check for non-null delivery dates to avoid skewing the results with incomplete data, which could lead to an inaccurate representation of customer delivery experiences.
-- Only 8.1% of customers never received a single order on time — that is actually a strong logistics performance. It means 91.9% of customers had at least one on-time delivery.

-- 5.  Which customer state generates the most revenue?
SELECT * FROM (
    SELECT 
        c.customer_state,
        ROUND(sum(order_total), 2) AS sum_order_value
    FROM orders o
    JOIN customers c ON c.customer_id = o.customer_id
    JOIN (
        SELECT order_id, SUM(price) AS order_total
        FROM order_items
        GROUP BY order_id
    ) AS order_totals ON order_totals.order_id = o.order_id
    GROUP BY c.customer_state
) AS city_orders
ORDER BY sum_order_value DESC
LIMIT 1

-- SP with  5,202,955.05 USD is the highest revenue generated by a single state, which indicates that this state has a strong customer base and high purchasing power. This insight can help the company focus its marketing and sales efforts on this state to further increase revenue and customer engagement. Additionally, understanding the factors contributing to this high revenue can provide valuable insights for expanding into similar markets or optimizing strategies in other states.